"""add recovery codes and shared message fields

Revision ID: 564ceb1dbea6
Revises: 
Create Date: 2026-05-05 23:44:44.281050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision: str = '564ceb1dbea6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message',sa.Column('message_type', sqlmodel.sql.sqltypes.AutoString(), server_default='text', nullable=False))
    op.add_column('message', sa.Column('shared_review_id', sa.Integer(), nullable=True))
    op.add_column('message', sa.Column('shared_movie_id', sa.Integer(), nullable=True))
    op.add_column('message', sa.Column('shared_song_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_message_message_type'), 'message', ['message_type'], unique=False)
    op.create_index(op.f('ix_message_shared_movie_id'), 'message', ['shared_movie_id'], unique=False)
    op.create_index(op.f('ix_message_shared_review_id'), 'message', ['shared_review_id'], unique=False)
    op.create_index(op.f('ix_message_shared_song_id'), 'message', ['shared_song_id'], unique=False)
    op.create_foreign_key("fk_message_shared_song", "message", "song", ["shared_song_id"], ["song_id"])
    op.create_foreign_key("fk_message_shared_review", "message", "review", ["shared_review_id"], ["review_id"])
    op.create_foreign_key("fk_message_shared_movie", "message", "movie", ["shared_movie_id"], ["movie_id"])
    op.add_column('user', sa.Column('recovery_code_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'recovery_code_hash')
    op.drop_constraint("fk_message_shared_movie", "message", type_="foreignkey")
    op.drop_constraint("fk_message_shared_review", "message", type_="foreignkey")
    op.drop_constraint("fk_message_shared_song", "message", type_="foreignkey")
    op.drop_index(op.f('ix_message_shared_song_id'), table_name='message')
    op.drop_index(op.f('ix_message_shared_review_id'), table_name='message')
    op.drop_index(op.f('ix_message_shared_movie_id'), table_name='message')
    op.drop_index(op.f('ix_message_message_type'), table_name='message')
    op.drop_column('message', 'shared_song_id')
    op.drop_column('message', 'shared_movie_id')
    op.drop_column('message', 'shared_review_id')
    op.drop_column('message', 'message_type')
    # ### end Alembic commands ###
