"""add back_drop field to model Movie

Revision ID: fa0e492d1a70
Revises: 
Create Date: 2026-03-29 15:50:42.442596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa0e492d1a70'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_friendship_addressee'), table_name='friendship')
    op.drop_index(op.f('ix_friendship_requester'), table_name='friendship')
    op.drop_index(op.f('ix_friendship_status'), table_name='friendship')
    op.drop_index(op.f('uq_friend_pair'), table_name='friendship')
    op.drop_index(op.f('ix_message_conversation_time'), table_name='message')
    op.drop_index(op.f('ix_conversation_dm_pair_updated'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_last_message_at'), table_name='conversation')
    op.drop_index(op.f('ix_member_conversation_active'), table_name='conversationmember')
    op.drop_index(op.f('ix_member_unread'), table_name='conversationmember')
    op.drop_index(op.f('ix_member_user_lookup'), table_name='conversationmember')
    op.drop_constraint(op.f('uq_conversation_dm_pair'), table_name='conversation')
    op.drop_table('conversationmember')
    op.execute("DROP TABLE message CASCADE")
    # op.drop_table('message')
    op.drop_table('conversation')
    op.drop_table('friendship')
    op.drop_table('songgenre')
    op.drop_table('moviedirector')
    op.drop_table('songartist')
    op.drop_table('movieactor')
    op.drop_table('moviewriter')
    op.drop_table('moviegenre')
    op.drop_table('artist')
    op.drop_table('review')
    op.drop_table('genre')
    op.drop_table('song')
    op.drop_table('actor')
    op.drop_table('episode')
    op.drop_table('writer')
    op.drop_table('director')
    op.drop_table('movie')
    op.drop_table('profile')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('user_pkey'))
    )
    op.create_table('profile',
                    sa.Column('profile_id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('profile_user_id_fkey')),
                    sa.PrimaryKeyConstraint('profile_id', name=op.f('profile_pkey'))
                    )
    op.create_table('movie',
    sa.Column('movie_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('movie_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('length', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cover', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('movie_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('movie_rating_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('movie_id', name=op.f('movie_pkey'))
    )
    op.create_table('actor',
                    sa.Column('actor_id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('actor_name', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('actor_id', name=op.f('actor_pkey'))
                    )
    op.create_table('song',
                    sa.Column('song_id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('song_name', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('length', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('cover', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('song_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
                    sa.Column('song_rating_count', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('song_id', name=op.f('song_pkey'))
                    )
    op.create_table('review',
                    sa.Column('review_id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('review', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('review_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
                    sa.Column('review_rating_count', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('song_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['movie_id'], ['movie.movie_id'], name=op.f('review_movie_id_fkey')),
                    sa.ForeignKeyConstraint(['song_id'], ['song.song_id'], name=op.f('review_song_id_fkey')),
                    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('review_user_id_fkey')),
                    sa.PrimaryKeyConstraint('review_id', name=op.f('review_pkey'))
                    )
    op.create_table('episode',
                    sa.Column('episode_id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('episode_name', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('season', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('episode_number', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['movie_id'], ['movie.movie_id'], name=op.f('episode_movie_id_fkey')),
                    sa.PrimaryKeyConstraint('episode_id', name=op.f('episode_pkey'))
                    )
    op.create_table('artist',
                    sa.Column('artist_id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('artist_name', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('artist_id', name=op.f('artist_pkey'))
                    )
    op.create_table('writer',
                    sa.Column('writer_id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('writer_name', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('writer_id', name=op.f('writer_pkey'))
                    )
    op.create_table('director',
                    sa.Column('director_id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('director_name', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('director_id', name=op.f('director_pkey'))
                    )
    op.create_table('genre',
                    sa.Column('genre_id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('genre_name', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('genre_id', name=op.f('genre_pkey'))
                    )
    op.create_table('songgenre',
                    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('song_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['genre_id'], ['genre.genre_id'], name=op.f('songgenre_genre_id_fkey')),
                    sa.ForeignKeyConstraint(['song_id'], ['song.song_id'], name=op.f('songgenre_song_id_fkey')),
                    sa.PrimaryKeyConstraint('genre_id', 'song_id', name=op.f('songgenre_pkey'))
                    )
    op.create_table('moviegenre',
                    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['genre_id'], ['genre.genre_id'], name=op.f('moviegenre_genre_id_fkey')),
                    sa.ForeignKeyConstraint(['movie_id'], ['movie.movie_id'], name=op.f('moviegenre_movie_id_fkey')),
                    sa.PrimaryKeyConstraint('movie_id', 'genre_id', name=op.f('moviegenre_pkey'))
                    )
    op.create_table('moviedirector',
                    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('director_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['director_id'], ['director.director_id'], name=op.f('moviedirector_director_id_fkey')),
                    sa.ForeignKeyConstraint(['movie_id'], ['movie.movie_id'], name=op.f('moviedirector_movie_id_fkey')),
                    sa.PrimaryKeyConstraint('movie_id', 'director_id', name=op.f('moviedirector_pkey'))
                    )
    op.create_table('moviewriter',
                    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('writer_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['movie_id'], ['movie.movie_id'], name=op.f('moviewriter_movie_id_fkey')),
                    sa.ForeignKeyConstraint(['writer_id'], ['writer.writer_id'], name=op.f('moviewriter_writer_id_fkey')),
                    sa.PrimaryKeyConstraint('movie_id', 'writer_id', name=op.f('moviewriter_pkey'))
                    )
    op.create_table('songartist',
                    sa.Column('song_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['artist_id'], ['artist.artist_id'], name=op.f('songartist_artist_id_fkey')),
                    sa.ForeignKeyConstraint(['song_id'], ['song.song_id'], name=op.f('songartist_song_id_fkey')),
                    sa.PrimaryKeyConstraint('song_id', 'artist_id', name=op.f('songartist_pkey'))
                    )
    op.create_table('movieactor',
                    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['actor_id'], ['actor.actor_id'], name=op.f('movieactor_actor_id_fkey')),
                    sa.ForeignKeyConstraint(['movie_id'], ['movie.movie_id'], name=op.f('movieactor_movie_id_fkey')),
                    sa.PrimaryKeyConstraint('movie_id', 'actor_id', name=op.f('movieactor_pkey'))
                    )

    
    op.create_table('conversationmember',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('joined_datetime', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
                    sa.Column('left_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
                    sa.Column('last_read_message_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('unread_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.conversation_id'], name=op.f('fk_member_conversation'), ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['last_read_message_id'], ['message.message_id'], name=op.f('fk_member_last_read_message'), ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('fk_member_user'), ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name=op.f('conversationmember_pkey')),
                    sa.UniqueConstraint('conversation_id', 'user_id', name=op.f('uq_conversation_member'), postgresql_include=[], postgresql_nulls_not_distinct=False)
                    )
    op.create_index(op.f('ix_member_user_lookup'), 'conversationmember', ['user_id', 'conversation_id'], unique=False)
    op.create_index(op.f('ix_member_unread'), 'conversationmember', ['user_id', 'unread_count'], unique=False)
    op.create_index(op.f('ix_member_conversation_active'), 'conversationmember', ['conversation_id', 'left_datetime'], unique=False)

    op.create_table('conversation',
                    sa.Column('conversation_id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('conversation_name', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('is_group', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
                    sa.Column('dm_user_low_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('dm_user_high_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
                    sa.Column('last_message_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('last_message_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
                    sa.Column('last_message_text', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('last_message_from_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.CheckConstraint('is_group = true AND dm_user_low_id IS NULL AND dm_user_high_id IS NULL OR is_group = false AND dm_user_low_id IS NOT NULL AND dm_user_high_id IS NOT NULL AND dm_user_low_id < dm_user_high_id', name=op.f('ck_conversation_dm_fields')),
                    sa.ForeignKeyConstraint(['dm_user_high_id'], ['user.user_id'], name=op.f('fk_conversation_high_user'), ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['dm_user_low_id'], ['user.user_id'], name=op.f('fk_conversation_low_user'), ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['last_message_from_user_id'], ['user.user_id'], name=op.f('fk_conversation_last_sender'), ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(['last_message_id'], ['message.message_id'], name=op.f('fk_conversation_last_message'), ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('conversation_id', name=op.f('conversation_pkey')),
                    sa.UniqueConstraint('dm_user_low_id', 'dm_user_high_id', name=op.f('uq_conversation_dm_pair'), postgresql_include=[], postgresql_nulls_not_distinct=False)
                    )
    op.create_index(op.f('ix_conversation_last_message_at'), 'conversation', [sa.literal_column('last_message_at DESC')], unique=False)
    op.create_index(op.f('ix_conversation_dm_pair_updated'), 'conversation', ['dm_user_low_id', 'dm_user_high_id', sa.literal_column('updated_at DESC')], unique=False)

    op.create_table('message',
                    sa.Column('message_id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('from_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('message_text', sa.TEXT(), autoincrement=False, nullable=False),
                    sa.Column('sent_datetime', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.conversation_id'], name=op.f('fk_message_conversation'), ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['from_user_id'], ['user.user_id'], name=op.f('fk_message_user'), ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('message_id', name=op.f('message_pkey'))
                    )
    op.create_index(op.f('ix_message_conversation_time'), 'message', ['conversation_id', 'sent_datetime'], unique=False)


    op.create_table('friendship',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('requester_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('addressee_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('user_low_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('user_high_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['addressee_id'], ['user.user_id'], name=op.f('friendship_addressee_id_fkey'), ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['requester_id'], ['user.user_id'], name=op.f('friendship_requester_id_fkey'), ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name=op.f('friendship_pkey'))
                    )
    op.create_index(op.f('uq_friend_pair'), 'friendship', ['user_low_id', 'user_high_id'], unique=True)
    op.create_index(op.f('ix_friendship_status'), 'friendship', ['status'], unique=False)
    op.create_index(op.f('ix_friendship_requester'), 'friendship', ['requester_id'], unique=False)
    op.create_index(op.f('ix_friendship_addressee'), 'friendship', ['addressee_id'], unique=False)
    # ### end Alembic commands ###
